
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name" : "santosh",
    "email": "rishi@anjaconline.org",
    "password": "123",
    "role":"admin"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "roshandavidr@anjaconline.org",
    "password": "123"
}

###

POST http://localhost:3000/auth/verifyOTP
Content-Type: application/json
Authorization: Bearer

{
    "otp": ""
}

### 

POST http://localhost:3000/products/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoicmlzaGkiLCJlbWFpbCI6InJpc2hpa2VzaGtAYW5qYWNvbmxpbmUub3JnIiwicm9sZSI6ImFkbWluIiwiaXNBY3RpdmUiOnRydWUsImlhdCI6MTcwNzI4MTM2NiwiZXhwIjoxNzA3Mjg0OTY2fQ.s60_IE7Q4gcu9eRfb7URkqQtVEBEBz0SPITQ4jt3YMo

{
  "email":"rishikeshk@anjaconline.org",
  "name": "t",
  "barcode": "526556",
  "isActive": true,
  "price": 10,
  "stock": 10,
  "lowStock": 20
}
###

POST http://localhost:3000/products/update
Content-Type: application/json

{
  "name": "tea",
  "newstock": 10
}

###

DELETE  http://localhost:3000/products/delete/657c1647d95c221c711f5a8c


###

POST http://localhost:3000/products
Content-Type: application/json

{
  "perpage":10,
  "page":1
}

###
POST http://localhost:3000/products/lowstack


###
GET http://localhost:3000/user/allusers

###
DELETE http://localhost:3000/user/allusers/rishikeshk@anjaconline.org

###
GET http://localhost:3000/bill/new-bill

###
POST http://localhost:3000/products/totalusers

###
POST  http://localhost:3000/bill/new-bill
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoicHJhYmhhIiwiZW1haWwiOiJrYXJhbnByYWJoYTIyNjY4QGdtYWlsLmNvbSIsInJvbGUiOiJjYXNoaWVyIiwiaXNBY3RpdmUiOnRydWUsImlhdCI6MTcxMDQ5MzE2NSwiZXhwIjoxNzEwNDk2NzY1LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAifQ.5kTEPzQ9PSJMlKJ9Isdn9rmJHcrhaw1-Yl8RQ1BrsSA

{
  "customerName":"roshan",
  "city":"sivakasi",
  "number":"9486012814",
  "items":[
        {
          "productName": "frooti",
          "quantity": 10,
          "unitPrice": 10,
          "totalPrice": 100
        },
        {
          "productName": "wewq",
          "quantity": 10,
          "unitPrice": 12340,
          "totalPrice": 123400
        }
      ],
    "totalAmount":12350
}


###
GET http://localhost:3000/products/allproducts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoicmlzaGkiLCJlbWFpbCI6InJpc2hpa2VzaGtAYW5qYWNvbmxpbmUub3JnIiwicm9sZSI6ImFkbWluIiwiaXNBY3RpdmUiOnRydWUsImlhdCI6MTcwNjUwODQ5MCwiZXhwIjoxNzA2NTEyMDkwfQ.Hpl-whdW0j8Iaxnk8VEhzsQbsYINooZa_BV4OnH3VEQ


###
POST http://localhost:3000/products/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoicmlzaGkiLCJlbWFpbCI6InJpc2hpa2VzaGtAYW5qYWNvbmxpbmUub3JnIiwicm9sZSI6ImFkbWluIiwiaXNBY3RpdmUiOnRydWUsImlhdCI6MTcwOTcwNTI3MiwiZXhwIjoxNzA5NzA4ODcyfQ.ieqMP-WHizTQ9bRizu3ZUnckrTkr0NGHlI2GHsIn9wU

{
  "name": "tea",
  "barcode":"3124542234",
  "isActive":true,
  "price":10,
  "stock":1000,
  "lowStock":100
} 

###
POST  http://localhost:3000/bill/allbills
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoicHJhYmhhIiwiZW1haWwiOiJrYXJhbnByYWJoYTIyNjY4QGdtYWlsLmNvbSIsInJvbGUiOiJjYXNoaWVyIiwiaXNBY3RpdmUiOnRydWUsImlhdCI6MTcxMDQ5MzE2NSwiZXhwIjoxNzEwNDk2NzY1LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAifQ.5kTEPzQ9PSJMlKJ9Isdn9rmJHcrhaw1-Yl8RQ1BrsSA

