
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name" : "santosh",
    "email": "rishi@anjaconline.org",
    "password": "123",
    "role":"admin"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "roshandavidr@anjaconline.org",
    "password": "123"
}

###

POST http://localhost:3000/auth/verifyOTP
Content-Type: application/json
Authorization: Bearer

{
    "otp": ""
}

### 

POST http://localhost:3000/products/add
Content-Type: application/json

{
  "email":"rishikeshk@anjaconline.org",
  "name": "taaa",
  "barcode": "526556",
  "measurement": "100gms",
  "isActive": true,
  "description": "tea pocket",
  "image": "img",
  "color": "brown",
  "price": 10,
  "stock": 10,
  "lowStock": 20
}
###

POST http://localhost:3000/products/update
Content-Type: application/json

{
  "name": "tea",
  "newstock": 10
}

###

DELETE  http://localhost:3000/products/delete/657c1647d95c221c711f5a8c


###

POST http://localhost:3000/products
Content-Type: application/json

{
  "perpage":10,
  "page":1
}

###
POST http://localhost:3000/products/lowstack


###
GET http://localhost:3000/user/allusers

###
DELETE http://localhost:3000/user/allusers/rishikeshk@anjaconline.org

###
GET http://localhost:3000/bill/new-bill

###
POST http://localhost:3000/products/totalusers

###
POST  http://localhost:3000/bill/new-bill
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoicmlzaGkiLCJlbWFpbCI6InJpc2hpa2VzaGtAYW5qYWNvbmxpbmUub3JnIiwicm9sZSI6ImFkbWluIiwiaXNBY3RpdmUiOnRydWUsImlhdCI6MTcwNjUwMzI4NCwiZXhwIjoxNzA2NTA2ODg0LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAifQ.9_sIGxLI97tQsvSt0-wEzXYoJVJmio1GvtoBg9YLBkY

{
  "customerName":"rishi",
  "items":[
        {
          "productName": "frooti",
          "quantity": 10,
          "unitPrice": 10
        }
      ],
    "totalAmount":10
}